### PR TITLE
Removed bug where subcategory remained null in case of duplicate Expense

### LINKED ISSUE #33: Bugs
- [x] A checked box means that the bug as been resolved

Bugs:
- [x] expense value can't have decimal numbers 
- [x] subcategory is empty when an expense is duplicated
- [x] Can create wallet with name null or empty
- [x] Public variables in three models

### PR DESCRIPTION
**Pull request by simo2898**
Added check to avoid NullPointerException if the subcategory is null

### CODE REVIEW

File: src/main/java/com/expensetracker/service/impl/ExpenseServiceImpl.java [hunk 1]
```diff
@@ -78,7 +77,7 @@ public Expense createNewExpense(Expense expense) {
         Category category = categoryRepository.findByName(expense.getCategory().getName());
         expense.setCategory(category);
 
-        if (expense.getSubcategory().getName() == null) {
+        if (expense.getSubcategory() == null || expense.getSubcategory().getName() == null) {
```
Comment (mattiapitossi) [inline src/main/java/com/expensetracker/service/impl/ExpenseServiceImpl.java]: if the subcategory exists shouldn't the name be mandatory?

**Review by mattiapitossi — CHANGES_REQUESTED** [review]

**Review by mattiapitossi — APPROVED** [review]
